# mdns / hostname.local discoverability
# ----------------------------------------
PACKAGES+=(
libnss3-dev
swig
python3-venv
python3-dev
python3-aniso8601
python3-attr
python3-automat
python3-cairocffi
python3-cairosvg
python3-click
python3-constantly
python3-cryptography
python3-cssselect
python3-dateutil
python3-defusedxml
python3-flask
python3-flask-restful
python3-future
python3-hyperlink
python3-incremental
python3-itsdangerous
python3-jinja2
python3-lxml
python3-mako
python3-netifaces
python3-pillow
python3-psycopg2
python3-hamcrest
python3-pyinotify
python3-openssl
python3-serial
python3-tz
python3-usb
python3-qrcode
python3-raven
python3-reportlab
python3-twisted
python3-werkzeug
python-xlwt
python3-zope.interface
)
